
🏆 E-Commerce Customer Retention & Profitability Analysis

Objective

Analyze customer purchasing behavior, identify retention problems, understand profitability drivers, and provide business recommendations to improve revenue and customer loyalty.
******************************************************************************************************************************************************************************************


Revenue Analysis
****************

Problem 1: What is the Total Revenue?

Business Problem:-
Management wants to know the total revenue generated by the company.

mysql> select sum(payment_value) as total_revenue from payments;
+---------------+
| total_revenue |
+---------------+
|   16008872.12 |
+---------------+
1 row in set (0.08 sec)

Business Insight

The company generated approximately 16 million in revenue during the analysis period
==========================================================================================================================================================================================
Problem 2: What is the Average Order Value (AOV)?
Business Problem

Finance wants to understand how much customers spend on average per order.

Problem 2: What is the Average Order Value (AOV)?

Business Problem
Finance wants to understand how much customers spend on average per order.

mysql> select sum(payment_value)/count(distinct order_id) as avgrage from payments;
+------------+
| avgrage    |
+------------+
| 160.990267 |
+------------+
1 row in set (0.54 sec)

Business Insight

Customers spend an average of 160.99 per order. 
==========================================================================================================================================================================================
Problem 3: Which Months Generated the Highest Revenue?
Business Problem

Management wants to identify the best-performing months to understand seasonality and plan future marketing campaigns.

mysql> select date_format(order_purchase_timestamp,'%Y-%m') as month, sum(payment_value) as revenue from orders join payments using(order_id) group by month order by revenue desc;
+---------+------------+
| month   | revenue    |
+---------+------------+
| 2017-11 | 1194882.80 |
| 2018-04 | 1160785.48 |
| 2018-03 | 1159652.12 |
| 2018-05 | 1153982.15 |
| 2018-01 | 1115004.18 |
| 2018-07 | 1066540.75 |
| 2018-06 | 1023880.50 |
| 2018-08 | 1022425.32 |
| 2018-02 |  992463.34 |
| 2017-12 |  878401.48 |
| 2017-10 |  779677.88 |
| 2017-09 |  727762.45 |
| 2017-08 |  674396.32 |
| 2017-05 |  592918.82 |
| 2017-07 |  592382.92 |
| 2017-06 |  511276.38 |
| 2017-03 |  449863.60 |
| 2017-04 |  417788.03 |
| 2017-02 |  291908.01 |
| 2017-01 |  138488.04 |
| 2016-10 |   59090.48 |
| 2018-09 |    4439.54 |
| 2018-10 |     589.67 |
| 2016-09 |     252.24 |
| 2016-12 |      19.62 |
+---------+------------+
25 rows in set (1.17 sec)

Business Insight

November 2017 was the highest revenue month.

Revenue: 1,194,882.80

This peak was likely influenced by events such as Black Friday promotions and holiday shopping.
Revenue generally increased throughout 2017 and remained strong during most of 2018.
The very low values in September 2018 and October 2018 are because the dataset contains incomplete data for those months.
==========================================================================================================================================================================================

Customer Analysis
*****************

Problem 4: How Many Repeat Customers Does the Company Have?
Business Problem

The company wants to measure customer retention.

mysql> select count(*) as repeat_cusotmer from (select customer_unique_id from customers join orders using(customer_id) group by customer_unique_id having count(order_id)>1)t;
+-----------------+
| repeat_cusotmer |
+-----------------+
|            2997 |
+-----------------+
1 row in set (1.33 sec)

Business Insight

Only a small percentage of customers return to make additional purchases.
==========================================================================================================================================================================================
Problem 5: How Many One-Time Customers Does the Company Have?
Business Problem

The company wants to identify how many customers purchase only once.

mysql> select count(*) as one_time_customer from ( select customer_unique_id from customers join orders using(customer_id) group by customer_unique_id having count(order_id)=1)t;
+-------------------+
| one_time_customer |
+-------------------+
|             93099 |
+-------------------+
1 row in set (1.38 sec)

Business Insight

Most customers purchase only once, indicating a customer retention issue
==========================================================================================================================================================================================
Problem 7:  Who Are the Top 10 Customers by Revenue?
Business Problem

Marketing wants to identify high-value customers for loyalty campaigns.

mysql> select customer_unique_id, sum(payment_value) as revenue from customers join orders using(customer_id) join payments using(order_id) group by customer_unique_id order by revenue desc limit 10;
+----------------------------------+----------+
| customer_unique_id               | revenue  |
+----------------------------------+----------+
| 0a0a92112bd4c708ca5fde585afaa872 | 13664.08 |
| 46450c74a0d8c5ca9395da1daac6c120 |  9553.02 |
| da122df9eeddfedc1dc1f5349a1a690c |  7571.63 |
| 763c8b1c9c68a0229c42c9fc6f662b93 |  7274.88 |
| dc4802a71eae9be1dd28f5d788ceb526 |  6929.31 |
| 459bef486812aa25204be022145caa62 |  6922.21 |
| ff4159b92c40ebe40454e3e6a7c35ed6 |  6726.66 |
| 4007669dec559734d6f53e029e360987 |  6081.54 |
| 5d0a2980b292d049061542014e8960bf |  4809.44 |
| eebb5dda148d3893cdaf5b5ca3040ccb |  4764.34 |
+----------------------------------+----------+
10 rows in set (2.44 sec)

Business Insight

A small group of customers contributes disproportionately to revenue and should be targeted with retention strategies.
==========================================================================================================================================================================================

Product Analysis
****************

Problem 8: Top 10 Product Categories by Revenue

Business Problem:

Which product categories generate the highest revenue?

mysql> select product_category_name, sum(price) as revenue from products join order_items using(product_id) group by product_category_name order by revenue desc limit 10 ;
+------------------------+------------+
| product_category_name  | revenue    |
+------------------------+------------+
| beleza_saude           | 1258681.34 |
| relogios_presentes     | 1205005.68 |
| cama_mesa_banho        | 1036988.68 |
| esporte_lazer          |  988048.97 |
| informatica_acessorios |  911954.32 |
| moveis_decoracao       |  729762.49 |
| cool_stuff             |  635290.85 |
| utilidades_domesticas  |  632248.66 |
| automotivo             |  592720.11 |
| ferramentas_jardim     |  485256.46 |
+------------------------+------------+
10 rows in set (0.84 sec)

Business Insights
🥇 Beauty & Health (beleza_saude)

Generated the highest revenue:

1,258,681.34

This indicates strong customer demand in this category.

⌚ Watches & Gifts (relogios_presentes)

Generated:

1,205,005.68

This suggests customers spend heavily on gift-oriented products.

🛏️ Bed, Bath & Table (cama_mesa_banho)

Crossed the 1 million revenue mark, making it another core category.
==========================================================================================================================================================================================
Problem 9: Top 10 Products by Revenue

Business Problem:

Which individual products contribute the most to sales?

mysql> select product_id, sum(price) as revenue from products join order_items using(product_id) group by product_id order by revenue desc limit 10;
+----------------------------------+----------+
| product_id                       | revenue  |
+----------------------------------+----------+
| bb50f2e236e5eea0100680137654686c | 63885.00 |
| 6cdd53843498f92890544667809f1595 | 54730.20 |
| d6160fb7873f184099d9bc95e30376af | 48899.34 |
| d1c427060a0f73f6b889a5c7c61f2ac4 | 47214.51 |
| 99a4788cb24856965c36a24e339b6058 | 43025.56 |
| 3dd2a17168ec895c781a9191c1e95ad7 | 41082.60 |
| 25c38557cf793876c5abdd5931f922db | 38907.32 |
| 5f504b3a1c75b73d6151be81eb05bdc9 | 37733.90 |
| 53b36df67ebb7c41585e8d54d6772e08 | 37683.42 |
| aca2eb7d00ea1a7b8ebd4e68314663af | 37608.90 |
+----------------------------------+----------+
10 rows in set (0.85 sec)

Business Insights:
 The highest revenue-generating product was bb50f2e236e5eea0100680137654686c, generating 63,885.00 in revenue.
 The top 10 products contribute a significant portion of total sales.
 These products should be prioritized for inventory management to avoid stock-outs.
 The company can use these products for promotions, cross-selling, and recommendation campaigns.
 Understanding why these products perform well can help replicate their success across other products.
 
==========================================================================================================================================================================================
Problem 10: Revenue Contribution by Category

Business Problem:

What percentage of total revenue does each category contribute?

mysql> SELECT product_category_name,
    ->        ROUND(SUM(price),2) AS revenue,
    ->        ROUND(SUM(price)*100/(SELECT SUM(price) FROM order_items),2) AS percentage
    -> FROM products
    -> JOIN order_items USING(product_id)
    -> GROUP BY product_category_name
    -> ORDER BY revenue DESC
    -> LIMIT 10;
+------------------------+------------+------------+
| product_category_name  | revenue    | percentage |
+------------------------+------------+------------+
| beleza_saude           | 1258681.34 |       9.26 |
| relogios_presentes     | 1205005.68 |       8.87 |
| cama_mesa_banho        | 1036988.68 |       7.63 |
| esporte_lazer          |  988048.97 |       7.27 |
| informatica_acessorios |  911954.32 |       6.71 |
| moveis_decoracao       |  729762.49 |       5.37 |
| cool_stuff             |  635290.85 |       4.67 |
| utilidades_domesticas  |  632248.66 |       4.65 |
| automotivo             |  592720.11 |       4.36 |
| ferramentas_jardim     |  485256.46 |       3.57 |
+------------------------+------------+------------+
10 rows in set (1.10 sec) 

Business Insights:
 Health & Beauty (beleza_saude) contributed the highest share of revenue, accounting for 9.26% of total sales.
 Watches & Gifts (relogios_presentes) generated 8.87% of total revenue.
 Bed, Bath & Table (cama_mesa_banho) contributed 7.63%.
 The top 5 categories together contributed nearly 40% of total revenue, showing that a few categories drive a large portion of the business.
 The company is highly dependent on these top-performing categories.

==========================================================================================================================================================================================

Seller Analysis
***************

Problem 11: Top 10 Sellers

Business Problem:

Which sellers generate the most revenue?

mysql> select seller_id,sum(price) as revenue from sellers join order_items using(seller_id) group by seller_id order by revenue desc limit 10;
+----------------------------------+-----------+
| seller_id                        | revenue   |
+----------------------------------+-----------+
| 4869f7a5dfa277a7dca6462dcf3b52b2 | 229472.63 |
| 53243585a1d6dc2643021fd1853d8905 | 222776.05 |
| 4a3ca9315b744ce9f8e9374361493884 | 200472.92 |
| fa1c13f2614d7b5c4749cbc52fecda94 | 194042.03 |
| 7c67e1448b00f6e969d365cea6b010ab | 187923.89 |
| 7e93a43ef30c4f03f38b393420bc753a | 176431.87 |
| da8622b14eb17ae2831f4ac5b9dab84a | 160236.57 |
| 7a67c85e85bb2ce8582c35f2203ad736 | 141745.53 |
| 1025f0e2d44d7041d6cf58b6550e0bfa | 138968.55 |
| 955fee9216a65b617aa5c0531780ce60 | 135171.70 |
+----------------------------------+-----------+
10 rows in set (0.61 sec)

Business Insights:
 Seller 4869f7a5dfa277a7dca6462dcf3b52b2 generated the highest revenue of 229,472.63.
 The top 10 sellers contribute a significant share of total sales.
 A small group of sellers are key revenue drivers for the business.
 Heavy dependence on a few sellers may increase business risk if they leave the platform.

==========================================================================================================================================================================================
Problem 12: Revenue by Seller State
Business Problem:

Which states have the highest seller revenue?

mysql> select seller_state,sum(price) as revenue from sellers join order_items using(seller_id) group by seller_state order by revenue desc ;
+--------------+------------+
| seller_state | revenue    |
+--------------+------------+
| SP           | 8753396.21 |
| PR           | 1261887.21 |
| MG           | 1011564.74 |
| RJ           |  843984.22 |
| SC           |  632426.07 |
| RS           |  378559.54 |
| BA           |  285561.56 |
| DF           |   97749.48 |
| PE           |   91493.85 |
| GO           |   66399.21 |
| ES           |   47689.61 |
| MA           |   36408.95 |
| CE           |   20240.64 |
| PB           |   17095.00 |
| MT           |   17070.72 |
| RN           |    9992.60 |
| MS           |    8551.69 |
| RO           |    4762.20 |
| PI           |    2522.00 |
| SE           |    1606.20 |
| PA           |    1238.00 |
| AM           |    1177.00 |
| AC           |     267.00 |
+--------------+------------+
23 rows in set (0.57 sec)

Business Insights
 São Paulo (SP) is the largest contributor, generating 8.75 million in revenue.
 Paraná (PR) ranks second with 1.26 million in revenue.
 Minas Gerais (MG) is third, contributing 1.01 million.
 The top 4 states (SP, PR, MG, RJ) account for the majority of seller revenue.
 Revenue is heavily concentrated in São Paulo, indicating dependence on one region.
==========================================================================================================================================================================================
